name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  DOCKER_REGISTRY: docker.io
  IMAGE_NAME_API: ebayclone/api
  IMAGE_NAME_WEB: ebayclone/web

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
    
    - name: Restore dependencies
      run: |
        dotnet restore EbayClone.API/EbayClone.API.csproj
        dotnet restore EbayClone.Web/EbayClone.Web.csproj
    
    - name: Build
      run: |
        dotnet build EbayClone.API/EbayClone.API.csproj --configuration Release --no-restore
        dotnet build EbayClone.Web/EbayClone.Web.csproj --configuration Release --no-restore
    
    - name: Run tests
      run: |
        dotnet test --no-restore --verbosity normal --collect:"XPlat Code Coverage"
    
    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      with:
        files: '**/coverage.cobertura.xml'

  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    needs: build-and-test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'sarif'
        output: 'trivy-results.sarif'
    
    - name: Upload Trivy results to GitHub Security
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: 'trivy-results.sarif'

  build-docker:
    name: Build Docker Images
    runs-on: ubuntu-latest
    needs: [build-and-test, security-scan]
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Extract metadata for API
      id: meta-api
      uses: docker/metadata-action@v4
      with:
        images: ${{ env.IMAGE_NAME_API }}
        tags: |
          type=ref,event=branch
          type=sha,prefix={{branch}}-
          type=semver,pattern={{version}}
          type=raw,value=latest,enable={{is_default_branch}}
    
    - name: Build and push API image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./EbayClone.API/Dockerfile
        push: true
        tags: ${{ steps.meta-api.outputs.tags }}
        labels: ${{ steps.meta-api.outputs.labels }}
        cache-from: type=registry,ref=${{ env.IMAGE_NAME_API }}:buildcache
        cache-to: type=registry,ref=${{ env.IMAGE_NAME_API }}:buildcache,mode=max
    
    - name: Extract metadata for Web
      id: meta-web
      uses: docker/metadata-action@v4
      with:
        images: ${{ env.IMAGE_NAME_WEB }}
        tags: |
          type=ref,event=branch
          type=sha,prefix={{branch}}-
          type=semver,pattern={{version}}
          type=raw,value=latest,enable={{is_default_branch}}
    
    - name: Build and push Web image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./EbayClone.Web/Dockerfile
        push: true
        tags: ${{ steps.meta-web.outputs.tags }}
        labels: ${{ steps.meta-web.outputs.labels }}
        cache-from: type=registry,ref=${{ env.IMAGE_NAME_WEB }}:buildcache
        cache-to: type=registry,ref=${{ env.IMAGE_NAME_WEB }}:buildcache,mode=max

  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: build-docker
    if: github.ref == 'refs/heads/develop'
    environment:
      name: staging
      url: https://staging.ebayclone.com
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Configure kubectl
      uses: azure/k8s-set-context@v3
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.KUBE_CONFIG_STAGING }}
    
    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s-deployment.yaml
        kubectl rollout status deployment/ebay-api -n staging
        kubectl rollout status deployment/ebay-web -n staging
    
    - name: Run smoke tests
      run: |
        kubectl run smoke-test --image=curlimages/curl --rm -i --restart=Never -- \
          curl -f http://ebay-web-service/health || exit 1

  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: build-docker
    if: github.ref == 'refs/heads/main'
    environment:
      name: production
      url: https://ebayclone.com
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Configure kubectl
      uses: azure/k8s-set-context@v3
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.KUBE_CONFIG_PRODUCTION }}
    
    - name: Deploy to Kubernetes (Blue-Green)
      run: |
        # Deploy to green environment
        kubectl apply -f k8s-deployment.yaml
        
        # Wait for rollout to complete
        kubectl rollout status deployment/ebay-api -n production --timeout=5m
        kubectl rollout status deployment/ebay-web -n production --timeout=5m
        
        # Run health checks
        kubectl run health-check --image=curlimages/curl --rm -i --restart=Never -- \
          curl -f http://ebay-web-service/health || exit 1
    
    - name: Notify deployment
      if: success()
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        text: 'Production deployment successful! 🚀'
        webhook_url: ${{ secrets.SLACK_WEBHOOK }}

  performance-test:
    name: Performance Testing (JMeter)
    runs-on: ubuntu-latest
    needs: deploy-staging
    if: github.ref == 'refs/heads/develop'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup JMeter
      run: |
        wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.6.2.tgz
        tar -xzf apache-jmeter-5.6.2.tgz
    
    - name: Run load tests
      run: |
        apache-jmeter-5.6.2/bin/jmeter -n -t tests/load-test.jmx \
          -l results.jtl \
          -Jhostname=staging.ebayclone.com \
          -Jthreads=100 \
          -Jrampup=60 \
          -Jduration=300
    
    - name: Generate HTML report
      run: |
        apache-jmeter-5.6.2/bin/jmeter -g results.jtl -o report/
    
    - name: Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: jmeter-results
        path: report/
    
    - name: Analyze results
      run: |
        # Check if error rate is below threshold
        ERROR_RATE=$(awk -F',' 'NR>1 {sum+=$8} END {print sum/NR}' results.jtl)
        if (( $(echo "$ERROR_RATE > 1" | bc -l) )); then
          echo "Error rate too high: $ERROR_RATE%"
          exit 1
        fi